### ISSUE TITLE
pkg-config error raised when running sdist

### ISSUE THREAD

**Issue by moorepants** [matthias-k/cyipopt#59]
```
moorepants@agni:~/src/cyipopt$ python setup.py sdist
Package ipopt was not found in the pkg-config search path.
Perhaps you should add the directory containing `ipopt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ipopt' found
Traceback (most recent call last):
  File "setup.py", line 101, in <module>
    **pkgconfig('ipopt'))]
  File "setup.py", line 57, in pkgconfig
    raise OSError(msg.format(list(packages)))
OSError: pkg-config was not able to find any of the requested packages ['ipopt'] on your system. Make sure pkg-config can discover the .pc files associated with the installed packages.
```

pkg-config should only be run when actually attempting to install.

**Comment by moorepants** [comment]
I think this is due to conda forge removing the `.pc` files. Closing in favor of #82.
