### ISSUE TITLE
PKG_CONFIG_PATH environment variable (install ipopt error)

### ISSUE THREAD

**Issue by annshorn** [matthias-k/cyipopt#69]
Hi, I tried to install ipopt trough pip install ipopt

Here is my error:

```
ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3w/zf3x85h55tv7qk2yg8ykztwc0000gn/T/pip-install-lnk4_998/ipopt/setup.py'"'"'; __file__='"'"'/private/var/folders/3w/zf3x85h55tv7qk2yg8ykztwc0000gn/T/pip-install-lnk4_998/ipopt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/3w/zf3x85h55tv7qk2yg8ykztwc0000gn/T/pip-pip-egg-info-h1me91bv
         cwd: /private/var/folders/3w/zf3x85h55tv7qk2yg8ykztwc0000gn/T/pip-install-lnk4_998/ipopt/
    Complete output (11 lines):
    Package ipopt was not found in the pkg-config search path.
    Perhaps you should add the directory containing `ipopt.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'ipopt' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3w/zf3x85h55tv7qk2yg8ykztwc0000gn/T/pip-install-lnk4_998/ipopt/setup.py", line 102, in <module>
        **pkgconfig('ipopt'))]
      File "/private/var/folders/3w/zf3x85h55tv7qk2yg8ykztwc0000gn/T/pip-install-lnk4_998/ipopt/setup.py", line 58, in pkgconfig
        raise OSError(msg.format(list(packages)))
    OSError: pkg-config was not able to find any of the requested packages ['ipopt'] on your system. Make sure pkg-config can discover the .pc files associated with the installed packages.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Command `pkg-config --variable pc_path pkg-config` gives:

`/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15`

Then `which pkg-config`:

`/usr/local/bin/pkg-config`

And making this doesn't solve the problem:

`export PKG_CONFIG_PATH=/usr/local/bin/pkg-config`

macOS Catalina 
python 3.7
pkg-config was installed through `brew install pkg-config`

**Comment by apommel** [comment]
Have you installed Ipopt (from brew or other source), if yes, what is your Ipopt version?

**Comment by annshorn** [comment]
I don't have Ipopt, when I tried to install it I get the error (above in the message)

**Comment by apommel** [comment]
This package is called ipopt on pip but it is a python/cython wrapper for the C++ optimization package Ipopt that must be downloaded as a dependence. On MacOS, you can install it with `brew install ipopt` (https://formulae.brew.sh/formula/ipopt).
After that, try again `pip install ipopt`.
